/* The following code was generated by JFlex 1.4.3 on 12/19/16 4:19 PM */

package com.gmail.devinz1993.smallc.frontend;

import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/19/16 4:19 PM from the specification file
 * <tt>smallc.lex</tt>
 */
class Lexer implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYCOMMENT = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\7\1\0\1\12\1\10\22\0\1\12\1\42\3\0"+
    "\1\47\1\53\1\0\1\34\1\35\1\46\1\43\1\32\1\44\1\33"+
    "\1\11\1\1\7\3\2\2\1\0\1\31\1\50\1\52\1\51\2\0"+
    "\6\5\21\6\1\4\2\6\1\36\1\0\1\37\1\54\1\6\1\0"+
    "\1\26\1\25\1\21\1\5\1\22\1\23\2\6\1\13\1\6\1\27"+
    "\1\24\1\6\1\14\1\30\2\6\1\17\1\16\1\15\1\20\2\6"+
    "\1\4\2\6\1\40\1\55\1\41\1\45\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\2\4\1\5\7\3\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\4\1\33\1\0\1\4"+
    "\1\34\1\35\1\3\1\36\6\3\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\1\63\4\3\1\64\1\3\1\65\1\66\3\3"+
    "\1\67\4\3\1\70\1\71\1\72\2\3\1\73";

  private static int [] zzUnpackAction() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\212\0\270\0\346\0\134\0\u0114"+
    "\0\u0142\0\u0170\0\u019e\0\u01cc\0\u01fa\0\u0228\0\u0256\0\u0284"+
    "\0\134\0\134\0\134\0\134\0\134\0\134\0\134\0\134"+
    "\0\134\0\u02b2\0\u02e0\0\u030e\0\134\0\u033c\0\u036a\0\u0398"+
    "\0\u03c6\0\u03f4\0\u0422\0\u0450\0\u047e\0\u04ac\0\u04da\0\u0508"+
    "\0\u0536\0\134\0\134\0\u0564\0\346\0\u0592\0\u05c0\0\u05ee"+
    "\0\u061c\0\u064a\0\u0678\0\134\0\134\0\134\0\134\0\134"+
    "\0\134\0\134\0\134\0\u06a6\0\134\0\u06d4\0\134\0\134"+
    "\0\134\0\134\0\134\0\134\0\134\0\134\0\u0508\0\346"+
    "\0\u0702\0\u0730\0\u075e\0\u078c\0\346\0\u07ba\0\134\0\134"+
    "\0\u07e8\0\u0816\0\u0844\0\346\0\u0872\0\u08a0\0\u08ce\0\u08fc"+
    "\0\346\0\346\0\346\0\u092a\0\u0958\0\346";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\3\6\1\7\1\10\1\11\1\7"+
    "\1\12\2\6\1\13\1\14\1\6\1\15\1\16\1\17"+
    "\1\6\1\20\3\6\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\46\7\1\46\7\7\57\0\1\47\1\0\1\47\1\50"+
    "\52\0\3\5\53\0\6\6\4\0\16\6\34\0\1\7"+
    "\57\0\1\51\34\0\1\52\3\0\1\53\4\0\6\6"+
    "\4\0\1\6\1\54\6\6\1\55\5\6\26\0\6\6"+
    "\4\0\2\6\1\56\13\6\26\0\6\6\4\0\7\6"+
    "\1\57\6\6\26\0\6\6\4\0\15\6\1\60\26\0"+
    "\6\6\4\0\11\6\1\61\4\6\26\0\6\6\4\0"+
    "\15\6\1\62\26\0\6\6\4\0\4\6\1\63\11\6"+
    "\77\0\1\64\46\0\1\65\6\0\1\66\47\0\1\67"+
    "\5\0\1\70\14\0\1\71\40\0\1\72\55\0\1\73"+
    "\53\0\1\74\1\0\1\75\54\0\1\76\1\77\55\0"+
    "\1\100\55\0\1\101\1\102\54\0\1\103\55\0\1\104"+
    "\2\0\1\105\11\0\1\106\45\0\1\47\1\0\1\47"+
    "\53\0\3\107\1\0\1\107\13\0\3\107\1\0\2\107"+
    "\27\0\7\51\1\7\1\10\45\51\1\0\6\6\4\0"+
    "\2\6\1\110\13\6\26\0\6\6\4\0\4\6\1\111"+
    "\11\6\26\0\6\6\4\0\2\6\1\112\13\6\26\0"+
    "\6\6\4\0\1\6\1\113\14\6\26\0\6\6\4\0"+
    "\3\6\1\114\12\6\26\0\6\6\4\0\4\6\1\115"+
    "\11\6\26\0\6\6\4\0\7\6\1\116\6\6\77\0"+
    "\1\117\55\0\1\120\4\0\6\6\4\0\5\6\1\121"+
    "\10\6\26\0\6\6\4\0\5\6\1\122\10\6\26\0"+
    "\6\6\4\0\2\6\1\123\13\6\26\0\6\6\4\0"+
    "\7\6\1\124\6\6\26\0\6\6\4\0\13\6\1\125"+
    "\2\6\26\0\6\6\4\0\6\6\1\126\7\6\26\0"+
    "\6\6\4\0\4\6\1\127\11\6\26\0\6\6\4\0"+
    "\1\130\15\6\26\0\6\6\4\0\14\6\1\131\1\6"+
    "\26\0\6\6\4\0\2\6\1\132\13\6\26\0\6\6"+
    "\4\0\1\6\1\133\14\6\26\0\6\6\4\0\1\6"+
    "\1\134\14\6\26\0\6\6\4\0\5\6\1\135\10\6"+
    "\26\0\6\6\4\0\7\6\1\136\6\6\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2438];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\3\1\1\11\11\1\11\11\3\1\1\11"+
    "\12\1\1\0\1\1\2\11\10\1\10\11\1\1\1\11"+
    "\1\1\10\11\10\1\2\11\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[94];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int tag) {
        return new Symbol(tag, yyline, yycolumn);
    }
    private Symbol symbol(int tag, Object value) {
        return new Symbol(tag, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, 	ParseError
 {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return symbol(RP);
          }
        case 60: break;
        case 17: 
          { return symbol(MINUS, new Term("-", yyline, yycolumn));
          }
        case 61: break;
        case 34: 
          { return symbol(DOUBLE_MINUS, new UniOp("--", yyline, yycolumn));
          }
        case 62: break;
        case 58: 
          { return symbol(RETURN);
          }
        case 63: break;
        case 13: 
          { return symbol(LC);
          }
        case 64: break;
        case 36: 
          { throw new ParseError("comment mismatch, extra '*/' found.", yyline, yycolumn);
          }
        case 65: break;
        case 37: 
          { return symbol(MULT_ASSIGN, new OpAssign("*=", yyline, yycolumn));
          }
        case 66: break;
        case 45: 
          { return symbol(AND, new BinOp("&&", yyline, yycolumn));
          }
        case 67: break;
        case 29: 
          { return symbol(DIV_ASSIGN, new OpAssign("/=", yyline, yycolumn));
          }
        case 68: break;
        case 23: 
          { return symbol(ASSIGN, new Assign("=", yyline, yycolumn));
          }
        case 69: break;
        case 8: 
          { return symbol(DOT);
          }
        case 70: break;
        case 11: 
          { return symbol(LB);
          }
        case 71: break;
        case 48: 
          { return symbol(OR, new BinOp("||", yyline, yycolumn));
          }
        case 72: break;
        case 7: 
          { return symbol(COMMA);
          }
        case 73: break;
        case 2: 
          { return symbol(INT, new CstNode(Integer.valueOf(yytext()), yyline, yycolumn));
          }
        case 74: break;
        case 39: 
          { return symbol(SL, new BinOp("<<", yyline, yycolumn));
          }
        case 75: break;
        case 51: 
          { return symbol(TYPE);
          }
        case 76: break;
        case 57: 
          { return symbol(STRUCT);
          }
        case 77: break;
        case 56: 
          { return symbol(BREAK, new IDNode(yytext(), yyline, yycolumn));
          }
        case 78: break;
        case 32: 
          { return symbol(DOUBLE_PLUS, new UniOp("++", yyline, yycolumn));
          }
        case 79: break;
        case 55: 
          { return symbol(ELSE);
          }
        case 80: break;
        case 33: 
          { return symbol(PLUS_ASSIGN, new OpAssign("+=", yyline, yycolumn));
          }
        case 81: break;
        case 16: 
          { return symbol(PLUS, new BinOp("+", yyline, yycolumn));
          }
        case 82: break;
        case 22: 
          { return symbol(GT, new BinOp(">", yyline, yycolumn));
          }
        case 83: break;
        case 47: 
          { return symbol(OR_ASSIGN, new OpAssign("|=", yyline, yycolumn));
          }
        case 84: break;
        case 49: 
          { yybegin(YYINITIAL);
          }
        case 85: break;
        case 15: 
          { return symbol(NOT, new UniOp("!", yyline, yycolumn));
          }
        case 86: break;
        case 26: 
          { return symbol(BIT_OR, new BinOp("|", yyline, yycolumn));
          }
        case 87: break;
        case 31: 
          { return symbol(NE, new BinOp("!=", yyline, yycolumn));
          }
        case 88: break;
        case 46: 
          { return symbol(XOR_ASSIGN, new OpAssign("^=", yyline, yycolumn));
          }
        case 89: break;
        case 5: 
          { return symbol(DIV, new BinOp("/", yyline, yycolumn));
          }
        case 90: break;
        case 59: 
          { return symbol(CONT, new IDNode(yytext(), yyline, yycolumn));
          }
        case 91: break;
        case 43: 
          { return symbol(EQ, new BinOp("==", yyline, yycolumn));
          }
        case 92: break;
        case 25: 
          { return symbol(BIT_XOR, new BinOp("^", yyline, yycolumn));
          }
        case 93: break;
        case 35: 
          { return symbol(MINUS_ASSIGN, new OpAssign("-=", yyline, yycolumn));
          }
        case 94: break;
        case 50: 
          { return symbol(INT, new CstNode(Integer.valueOf(yytext().substring(2), 16), yyline, yycolumn));
          }
        case 95: break;
        case 6: 
          { return symbol(SEMI);
          }
        case 96: break;
        case 18: 
          { return symbol(BIT_NOT, new UniOp("~", yyline, yycolumn));
          }
        case 97: break;
        case 14: 
          { return symbol(RC);
          }
        case 98: break;
        case 44: 
          { return symbol(AND_ASSIGN, new OpAssign("&=", yyline, yycolumn));
          }
        case 99: break;
        case 3: 
          { return symbol(ID, new IDNode(yytext(), yyline, yycolumn));
          }
        case 100: break;
        case 30: 
          { return symbol(IF, new IDNode(yytext(), yyline, yycolumn));
          }
        case 101: break;
        case 9: 
          { return symbol(LP);
          }
        case 102: break;
        case 24: 
          { return symbol(BIT_AND, new BinOp("&", yyline, yycolumn));
          }
        case 103: break;
        case 12: 
          { return symbol(RB);
          }
        case 104: break;
        case 40: 
          { return symbol(NGT, new BinOp("<=", yyline, yycolumn));
          }
        case 105: break;
        case 20: 
          { return symbol(MOD, new BinOp("%", yyline, yycolumn));
          }
        case 106: break;
        case 28: 
          { yybegin(YYCOMMENT);
          }
        case 107: break;
        case 53: 
          { return symbol(SL_ASSIGN, new OpAssign("<<=", yyline, yycolumn));
          }
        case 108: break;
        case 41: 
          { return symbol(SR, new BinOp(">>", yyline, yycolumn));
          }
        case 109: break;
        case 19: 
          { return symbol(MULT, new BinOp("*", yyline, yycolumn));
          }
        case 110: break;
        case 52: 
          { return symbol(FOR);
          }
        case 111: break;
        case 1: 
          { throw new ParseError("illegal character '"+yychar+"'.", yyline, yycolumn);
          }
        case 112: break;
        case 21: 
          { return symbol(LT, new BinOp("<", yyline, yycolumn));
          }
        case 113: break;
        case 42: 
          { return symbol(NLT, new BinOp(">=", yyline, yycolumn));
          }
        case 114: break;
        case 27: 
          { return symbol(INT, new CstNode(Integer.valueOf(yytext().substring(1), 8), yyline, yycolumn));
          }
        case 115: break;
        case 38: 
          { return symbol(MOD_ASSIGN, new OpAssign("%=", yyline, yycolumn));
          }
        case 116: break;
        case 54: 
          { return symbol(SR_ASSIGN, new OpAssign(">>=", yyline, yycolumn));
          }
        case 117: break;
        case 4: 
          { 
          }
        case 118: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     if (yystate() == YYCOMMENT) {
        throw new ParseError("Comment mismatch, need */ at EOF.", yyline, yycolumn);
    }
    return symbol(EOF, null);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
