
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Dec 19 16:19:08 PST 2016
//----------------------------------------------------

package com.gmail.devinz1993.smallc.frontend;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int BIT_XOR = 14;
  public static final int CONT = 4;
  public static final int XOR_ASSIGN = 35;
  public static final int SR = 23;
  public static final int MULT = 25;
  public static final int SL = 22;
  public static final int PLUS_ASSIGN = 29;
  public static final int BIT_NOT = 10;
  public static final int BIT_AND = 15;
  public static final int SEMI = 45;
  public static final int INT = 6;
  public static final int FOR = 44;
  public static final int MINUS = 39;
  public static final int NLT = 20;
  public static final int NOT = 7;
  public static final int AND = 12;
  public static final int DOUBLE_MINUS = 9;
  public static final int LT = 19;
  public static final int TYPE = 40;
  public static final int LOWER_THAN_ELSE = 54;
  public static final int LP = 50;
  public static final int OR = 11;
  public static final int COMMA = 46;
  public static final int RP = 51;
  public static final int DIV = 26;
  public static final int PLUS = 24;
  public static final int ASSIGN = 28;
  public static final int IF = 5;
  public static final int DOT = 49;
  public static final int SR_ASSIGN = 37;
  public static final int ID = 2;
  public static final int LC = 47;
  public static final int EOF = 0;
  public static final int LB = 52;
  public static final int RETURN = 42;
  public static final int RC = 48;
  public static final int error = 1;
  public static final int RB = 53;
  public static final int MOD = 27;
  public static final int BREAK = 3;
  public static final int EQ = 16;
  public static final int DIV_ASSIGN = 32;
  public static final int MOD_ASSIGN = 33;
  public static final int ELSE = 43;
  public static final int DOUBLE_PLUS = 8;
  public static final int AND_ASSIGN = 34;
  public static final int OR_ASSIGN = 36;
  public static final int NE = 17;
  public static final int BIT_OR = 13;
  public static final int NGT = 21;
  public static final int STRUCT = 41;
  public static final int MULT_ASSIGN = 31;
  public static final int GT = 18;
  public static final int MINUS_ASSIGN = 30;
  public static final int SL_ASSIGN = 38;
}

